### ISSUE TITLE
Polygon to bounding Box

### ISSUE THREAD

**Issue by cubecleveland** [plepe/boundingbox#13]
Hi, we are using leafelt and i was wndering givent the latlng object of the polygon ( sometime has 9, 10 coords) we can get the box as a rectangle.....? if so how would we pass the entire coord set ?

**Comment by plepe** [comment]
There's a getBounds() function for Leaflet Polygons (inherited from Polyline), so I don't see why BoundingBox should implement this too.

-> https://leafletjs.com/reference.html#polygon

**Comment by cubecleveland** [comment]
Many thanks!
